### ISSUE TITLE
Any hope of code to produce this for a specific profile?

### ISSUE THREAD

**Issue by zxsdklfhskyrvk** [andruzzzhka/BeatSaberScrappedData#1]
UPDATE:
Here is my python based scraper, for anyone interested. Based on the ScoreSaber website as of 7/5/2019. Runs on the latest 3.x Python. Dependencies - requests, html5lib and bs4

https://github.com/andruzzzhka/BeatSaberScrappedData/files/3363695/ScoreSaber-UserProfile-Scraper.py.txt

**Comment by andruzzzhka** [comment]
[Here you go!](https://github.com/andruzzzhka/BeatSaberScrappedData/files/3361064/BeatSaberScrapper.zip)

**Comment by zxsdklfhskyrvk** [comment]
Thanks for the share!  Rats, I guess there is no API access to a users profile.  That means I have to scrape the site myself.

**Comment by ithirzty** [comment]
By reverse engineering their api client (https://github.com/wwisser/scoresaber-api-client/blob/master/src/client.ts), here is a more polished way to do it : simply make a request ti this url : 
https://new.scoresaber.com/api/player/YOUR-ID/full
