### ISSUE TITLE
Missing some maps

### ISSUE THREAD

**Issue by ibillingsley** [andruzzzhka/BeatSaberScrappedData#11]
I noticed a few maps I have are missing from combinedScrappedData.json (and presumably the Protobuf data).
These are not new, outdated, or deleted.

https://beatsaver.com/maps/2bad2
https://beatsaver.com/maps/27bfd
https://beatsaver.com/maps/2ef1a
https://beatsaver.com/maps/2c348
https://beatsaver.com/maps/27cee
https://beatsaver.com/maps/27ca5
https://beatsaver.com/maps/32c07
https://beatsaver.com/maps/31fb3
https://beatsaver.com/maps/27ca4
https://beatsaver.com/maps/2c401
https://beatsaver.com/maps/2bba3
https://beatsaver.com/maps/32b94
https://beatsaver.com/maps/2c8a2
https://beatsaver.com/maps/3026f
https://beatsaver.com/maps/2c4cb

Not sure if there's anything special about these particular maps, or even if this data is intended to be 100% complete.
Maybe they were unpublished at one point and then republished?

**Comment by kinsi55** [comment]
Theres some long running issue in the scraper where some maps are just missing - I have yet to find the cause for this

**Comment by kinsi55** [comment]
I have given it another look just now and I believe to have found the issue - Or at the very least significantly improved upon it. This will be reflected in the dataset at some point soon as I'm working on an updated format for Songdetails / Proto to include some new stuff

**Comment by kinsi55** [comment]
The fix is now applied, lmk if you should still happen to find missing maps

**Comment by ibillingsley** [comment]
Awesome, I can confirm all 4000+ maps in my library are now present.  
(I can check by sorting BetterSongList by BeatSaver Date. Missing, outdated, or deleted maps end up at the bottom)
