### ISSUE TITLE
Include characteristics and additional information from beatsaver

### ISSUE THREAD

**Issue by Luux** [andruzzzhka/BeatSaberScrappedData#3]
Could you provide more extensive information from beatsaver? I want to include a filter for specific game modes in my tool ARBSMapDo (https://github.com/Luux/ARBSMapDo). Since for example OneSaber maps are extremely rare, I don't want to spam beatsaver and making hundreds of requests before even getting one valid result. It would be nice to rely on a daily scrape for that purpose, but unfortunately, this kind of information seems to be stripped away from the beatsaver results here.

**Comment by andruzzzhka** [comment]
Done!
